<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <Import Project="..\Lib\Rydia\Rydia.projitems" Label="Shared" />

  <Import Project="..\Lib\Rydia.Diagnostics\Rydia.Diagnostics.projitems" Label="Shared" />

  <Import Project="..\Lib\Rydia.Primitives\Rydia.Primitives.projitems" Label="Shared" />

  <Import Project="..\Rydia.Runtime.Core\Rydia.Runtime.Core.projitems" Label="Shared" />

  <Import Project="..\Lib\Rydia.Serialization\Rydia.Serialization.projitems" Label="Shared" />

  <Import Project="..\Lib\Rydia.Randomizer\Rydia.Randomizer.projitems" Label="Shared" />

</Project>
