<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="x64\SoXWrapper_x64.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="x86\SoXWrapper_x86.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="AdamsLair.TreeViewAdv" Version="1.7.7" />
		<PackageReference Include="SixLabors.ImageSharp" Version="2.1.11" />
		<PackageReference Include="SixLabors.ImageSharp.Drawing" Version="1.0.0" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="x64\" />
	  <Folder Include="x86\" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\Platform\Rydia.Runtime.Windows\Rydia.Runtime.Windows.csproj" />
	</ItemGroup>

	<Import Project="..\..\Runtime\Samples\SampleEngine\SampleEngine.projitems" Label="Shared" />
</Project>